# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713e64166784637dd41b754d8b4849b66ac392ce16a0bba9946de26f966e09f78083b28ff49944af71cb9fcdc9a0f759fc7f0412180449d151bf22f16560b0c4

test:
  secret_key_base: 7c4f71296041d2bc3bd905b33f4d4a5401d665cf9089f0538f6db435f49969a8a450cbc5d2cb984fd1b53d08dc2bb41859cebe4e1e3ca279f41c5a30ca910aa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
